Repository magley/mocker-hub, pull requests merged in 2025-07, with the labels that each got.

#45 Feature delete repository
  .github/workflows/run_tests.yml
  client/src/api/repo.api.ts
  client/src/components/RepoSettings.tsx
  compose.yaml
  server/app/api/access_control/access_control_service.py
  server/app/api/config/initialize.py
  server/app/api/config/worker.py
  server/app/api/jobs/__init__.py
  server/app/api/jobs/jobs_client.py
  server/app/api/jobs/jobs_service.py
  server/app/api/main.py
  server/app/api/registry/registry_controller.py
  server/app/api/registry/registry_dto.py
  server/app/api/registry/registry_service.py
  server/app/api/repo/repo_model.py
  server/app/api/repo/repo_repo.py
  server/app/api/repo/repo_service.py
  server/app/api/tags/tag_model.py
  server/app/api/team/team_model.py
  server/app/tests/test_jobs.py
  server/app/tests/test_registry.py
  server/app/tests/test_repository.py
  server/requirements.txt
Labels: enhancement

#47 Feature delete organization
  client/src/api/org.api.ts
  client/src/components/OrgSettings.tsx
  server/app/api/access_control/access_control_service.py
  server/app/api/org/org_model.py
  server/app/api/org/org_repo.py
  server/app/api/org/org_service.py
  server/app/api/registry/registry_controller.py
  server/app/api/registry/registry_service.py
  server/app/api/team/team_model.py
  server/app/tests/test_organization.py
  server/app/tests/test_registry.py
Labels: enhancement

#49 Feature update organization description
  client/src/api/org.api.ts
  client/src/components/OrgOverview.tsx
  client/src/components/OrgSettings.tsx
  client/src/components/RepoOverview.tsx
  client/src/pages/OrgPage.tsx
  compose.yaml
  server/app/api/org/org_controller.py
  server/app/api/org/org_dto.py
  server/app/api/org/org_service.py
  server/app/tests/test_organization.py
Labels: enhancement

#51 Bugfix, superadmin password change error message is ugly
  client/src/pages/UserPasswordChangeRequired.tsx
Labels: bug

#54 Fix ugly error message from Pydantic validation
  client/src/pages/UserAdminRegistration.tsx
  client/src/pages/UserPasswordChangeRequired.tsx
  client/src/pages/UserRegistration.tsx
  client/src/util/http.ts
  server/Dockerfile
  server/app/api/config/exception_handler.py
Labels: bug

#57 Feat ci cd improvements
  .github/workflows/run_tests.yml
  .github/workflows/test_and_deploy.yml
  README.md
  compose.yaml
  docs/.gitkeep
Labels: bug, enhancement

#58 Feature organization members
  client/src/api/org.api.ts
  client/src/api/user.api.ts
  client/src/components/OrgMembers.css
  client/src/components/OrgMembers.tsx
  client/src/pages/OrgPage.tsx
  server/app/api/org/org_controller.py
  server/app/api/org/org_repo.py
  server/app/api/org/org_service.py
  server/app/api/user/user_controller.py
  server/app/api/user/user_repo.py
  server/app/api/user/user_service.py
  server/app/tests/test_organization.py
  server/app/tests/test_user.py
Labels: enhancement

#62 Feature user profile
  client/src/App.tsx
  client/src/api/user.api.ts
  client/src/components/Navbar.tsx
  client/src/components/OrgMembers.tsx
  client/src/pages/ProfilePage.tsx
  client/src/pages/RepoOfUser.tsx
  client/src/pages/UserPasswordChange.tsx
  server/app/api/user/user_controller.py
  server/app/api/user/user_dto.py
  server/app/api/user/user_model.py
  server/app/api/user/user_service.py
  server/app/tests/test_user.py
Labels: enhancement

#66 Feature explore page
  client/src/App.tsx
  client/src/api/repo.api.ts
  client/src/components/Navbar.tsx
  client/src/components/RepoPreview.tsx
  client/src/pages/Explore.css
  client/src/pages/Explore.tsx
  client/src/pages/RepoOfUser.tsx
  client/src/pages/RepoStarred.tsx
  server/app/api/repo/repo_controller.py
  server/app/api/repo/repo_dto.py
  server/app/api/repo/repo_repo.py
  server/app/api/repo/repo_service.py
  server/app/tests/test_repository.py
Labels: enhancement
