Repository magley/mocker-hub, pull requests merged in 2025-08, with the labels that each got.

#70 fix: Properly rewind log collector
  log_collector/log_collector.py
Labels: bug

#69 Feature teams section
  client/src/api/org.api.ts
  client/src/api/repo.api.ts
  client/src/api/team.api.ts
  client/src/components/OrgMembers.tsx
  client/src/components/OrgOverview.tsx
  client/src/components/OrgTeams.css
  client/src/components/OrgTeams.tsx
  client/src/components/TeamDetails.css
  client/src/components/TeamDetails.tsx
  client/src/pages/OrgPage.tsx
  server/app/api/org/org_controller.py
  server/app/api/org/org_dto.py
  server/app/api/org/org_repo.py
  server/app/api/org/org_service.py
  server/app/api/repo/repo_controller.py
  server/app/api/repo/repo_repo.py
  server/app/api/repo/repo_service.py
  server/app/api/team/team_controller.py
  server/app/api/team/team_dto.py
  server/app/api/team/team_repo.py
  server/app/api/team/team_service.py
  server/app/tests/test_organization.py
  server/app/tests/test_team.py
Labels: enhancement

#75 Feature organization repositories
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/repo.api.ts
  client/src/components/Navbar.tsx
  client/src/components/OrgRepositories.tsx
  client/src/components/RepoOverview.tsx
  client/src/components/RepoPreview.tsx
  client/src/components/RepoTags.tsx
  client/src/components/TeamDetails.tsx
  client/src/pages/OrgOfUser.tsx
  client/src/pages/OrgPage.tsx
  client/src/pages/RepoCreate.css
  client/src/pages/RepoCreate.tsx
  client/src/pages/RepoOfUser.tsx
  client/src/pages/RepoPage.css
  client/src/pages/UserLogin.tsx
  server/app/api/access_control/access_control_service.py
  server/app/api/registry/registry_controller.py
  server/app/api/registry/registry_service.py
  server/app/api/repo/repo_controller.py
  server/app/api/repo/repo_dto.py
  server/app/api/repo/repo_service.py
  server/app/api/team/team_service.py
  server/app/tests/test_access_control.py
  server/app/tests/test_registry.py
  server/app/tests/test_repository.py
Labels: enhancement

#79 Feature model
  README.md
  docs/class_diagram.pdf
  docs/screenshots/Sprite-0001.png
  docs/screenshots/Sprite-0002.png
  docs/screenshots/Sprite-0003.png
  docs/screenshots/Sprite-0004.png
  docs/screenshots/Sprite-0005.png
  docs/screenshots/Sprite-0006.png
  docs/screenshots/Sprite-0007.png
  docs/screenshots/Sprite-0008.png
  docs/screenshots/Sprite-0009.png
  docs/screenshots/Sprite-0010.png
  docs/screenshots/Sprite-0011.png
  docs/screenshots/Sprite-0012.png
  docs/screenshots/Sprite-0013.png
  docs/screenshots/Sprite-0014.png
  docs/screenshots/Sprite-0015.png
  docs/screenshots/Sprite-0016.png
  docs/screenshots/Sprite-0017.png
  docs/screenshots/Sprite-0018.png
  docs/screenshots/Sprite-0019.png
  docs/screenshots/Sprite-0020.png
  docs/uml_uks.drawio
Labels: documentation
